from dataclasses import dataclass

from langchain_core.documents import Document
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_openai import ChatOpenAI

from app.config import get_settings, validate_settings
from app.prompts import RAG_PROMPT
from app.vector_store import VectorStoreManager


@dataclass
class RAGResponse:
    """
    Structured response returned by the RAG pipeline.

    answer:
        Final answer generated by the LLM.

    sources:
        List of metadata dictionaries for retrieved chunks.

    retrieved_documents:
        Raw retrieved LangChain Document objects.
    """

    answer: str
    sources: list[dict]
    retrieved_documents: list[Document]


class RAGPipeline:
    """
    End-to-end Retrieval-Augmented Generation pipeline.

    Responsibilities:
    - Load the existing FAISS index
    - Retrieve relevant chunks for a user question
    - Format retrieved context
    - Send context + question to the LLM
    - Return final answer with sources
    """

    def __init__(self) -> None:
        self.settings = get_settings()
        validate_settings(self.settings)

        self.llm = self._create_llm()
        self.vector_store_manager = VectorStoreManager()
        self.retriever = self.vector_store_manager.get_retriever()

    def _create_llm(self):
        """
        Create the chat model based on project settings.
        """
        if self.settings.primary_llm_provider == "openai":
            return ChatOpenAI(
                model=self.settings.openai_model,
                temperature=0.2,
                api_key=self.settings.openai_api_key,
            )

        if self.settings.primary_llm_provider == "gemini":
            return ChatGoogleGenerativeAI(
                model=self.settings.gemini_model,
                temperature=0.2,
                google_api_key=self.settings.google_api_key,
            )

        raise ValueError(
            f"Unsupported LLM provider: "
            f"{self.settings.primary_llm_provider}"
        )

    def ask(self, question: str) -> RAGResponse:
        """
        Answer a user question using retrieved document context.
        """
        cleaned_question = question.strip()

        if not cleaned_question:
            raise ValueError("Question cannot be empty.")

        retrieved_documents = self.retriever.invoke(cleaned_question)

        context = self._format_context(retrieved_documents)

        prompt_messages = RAG_PROMPT.format_messages(
            question=cleaned_question,
            context=context,
        )

        llm_response = self.llm.invoke(prompt_messages)

        sources = self._extract_sources(retrieved_documents)

        return RAGResponse(
            answer=llm_response.content,
            sources=sources,
            retrieved_documents=retrieved_documents,
        )

    def _format_context(self, documents: list[Document]) -> str:
        """
        Convert retrieved documents into a clean context string.
        """
        if not documents:
            return "No relevant context was retrieved."

        context_parts = []

        for index, doc in enumerate(documents, start=1):
            file_name = doc.metadata.get("file_name", "unknown file")
            page = doc.metadata.get("page", "N/A")
            chunk_id = doc.metadata.get("chunk_id", "N/A")

            context_parts.append(
                f"[Source {index}]\n"
                f"File: {file_name}\n"
                f"Page: {page}\n"
                f"Chunk ID: {chunk_id}\n"
                f"Content:\n{doc.page_content}"
            )

        return "\n\n".join(context_parts)

    def _extract_sources(self, documents: list[Document]) -> list[dict]:
        """
        Extract clean and readable source information.

        Each source includes a short preview so the user can verify
        which part of the document was used by the RAG system.
        """
        sources = []

        for doc in documents:
            preview = self._create_preview(doc.page_content)

            sources.append(
                {
                    "file_name": doc.metadata.get("file_name", "unknown"),
                    "file_type": doc.metadata.get("file_type", "unknown"),
                    "page": doc.metadata.get("page", "N/A"),
                    "chunk_id": doc.metadata.get("chunk_id", "N/A"),
                    "preview": preview,
                    "source": doc.metadata.get("source", "unknown"),
                }
            )

        return sources

    def _create_preview(
        self,
        text: str,
        max_length: int = 220,
    ) -> str:
        """
        Create a short readable preview from retrieved text.
        """
        cleaned_text = " ".join(text.split())

        if len(cleaned_text) <= max_length:
            return cleaned_text

        return cleaned_text[:max_length].rstrip() + "..."


if __name__ == "__main__":
    pipeline = RAGPipeline()

    question = "What is Retrieval-Augmented Generation?"
    response = pipeline.ask(question)

    print("Question:")
    print(question)

    print("\nAnswer:")
    print(response.answer)

    print("\nSources:")
    for source in response.sources:
        print(source)