from dataclasses import dataclass
from pathlib import Path

from openai import OpenAI

from app.config import get_settings, validate_settings
from app.image_loader import ImageLoader, LoadedImage
from app.prompts import (
    DEFAULT_IMAGE_ANALYSIS_QUESTION,
    VISION_SYSTEM_PROMPT,
)


@dataclass
class VisionResponse:
    """
    Structured response returned by the vision pipeline.

    answer:
        Final answer generated by the vision model.

    image_metadata:
        Basic metadata about the processed image.

    question:
        User question sent to the model.
    """

    answer: str
    image_metadata: dict
    question: str


class VisionPipeline:
    """
    End-to-end image understanding pipeline.

    Responsibilities:
    - Load image from disk
    - Convert image to Base64
    - Send image + question to a vision-capable model
    - Return answer with image metadata
    """

    def __init__(self) -> None:
        self.settings = get_settings()
        validate_settings(self.settings)

        self.image_loader = ImageLoader()

        if self.settings.vision_provider != "openai":
            raise ValueError(
                "This pipeline currently supports only "
                "VISION_PROVIDER=openai. Gemini support can be added later."
            )

        self.client = OpenAI(api_key=self.settings.openai_api_key)

    def analyze_image(
        self,
        image_path: str | Path,
        question: str | None = None,
    ) -> VisionResponse:
        """
        Analyze an image using a vision-capable model.
        """
        loaded_image = self.image_loader.load_image(image_path)
        clean_question = self._prepare_question(question)

        answer = self._call_openai_vision(
            loaded_image=loaded_image,
            question=clean_question,
        )

        return VisionResponse(
            answer=answer,
            image_metadata=self._extract_image_metadata(loaded_image),
            question=clean_question,
        )

    def _prepare_question(self, question: str | None) -> str:
        """
        Prepare the question sent to the vision model.
        """
        if question is None or not question.strip():
            return DEFAULT_IMAGE_ANALYSIS_QUESTION.strip()

        return question.strip()

    def _call_openai_vision(
        self,
        loaded_image: LoadedImage,
        question: str,
    ) -> str:
        """
        Call OpenAI vision model with image and question.
        """
        image_data_url = (
            f"data:{loaded_image.mime_type};base64,"
            f"{loaded_image.base64_data}"
        )

        response = self.client.chat.completions.create(
            model=self.settings.openai_vision_model,
            temperature=0.2,
            messages=[
                {
                    "role": "system",
                    "content": VISION_SYSTEM_PROMPT,
                },
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "text",
                            "text": question,
                        },
                        {
                            "type": "image_url",
                            "image_url": {
                                "url": image_data_url,
                            },
                        },
                    ],
                },
            ],
        )

        message = response.choices[0].message.content

        if not message:
            raise ValueError("Vision model returned an empty response.")

        return message

    def _extract_image_metadata(
        self,
        loaded_image: LoadedImage,
    ) -> dict:
        """
        Extract clean image metadata for the response.
        """
        return {
            "file_name": loaded_image.file_name,
            "file_extension": loaded_image.file_extension,
            "width": loaded_image.width,
            "height": loaded_image.height,
            "mode": loaded_image.mode,
            "mime_type": loaded_image.mime_type,
        }


if __name__ == "__main__":
    from app.config import UPLOADED_IMAGES_DIR, ensure_directories
    from app.image_loader import SUPPORTED_IMAGE_EXTENSIONS

    ensure_directories()

    image_files = [
        path
        for path in UPLOADED_IMAGES_DIR.iterdir()
        if path.is_file()
        and path.suffix.lower() in SUPPORTED_IMAGE_EXTENSIONS
    ]

    if not image_files:
        print(f"No supported images found in: {UPLOADED_IMAGES_DIR}")
        print("Add a test image first, then run this file again.")
    else:
        pipeline = VisionPipeline()
        response = pipeline.analyze_image(
            image_path=image_files[0],
            question="Analyze this image and explain what it shows.",
        )

        print("Question:")
        print(response.question)

        print("\nAnswer:")
        print(response.answer)

        print("\nImage metadata:")
        print(response.image_metadata)